# Generated by Django 5.0.6 on 2024-05-28 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='courses_api.section'),
            preserve_default=False,
        ),
    ]
